### ISSUE TITLE
Always return error

### ISSUE THREAD

**Issue by robertnicjoo** [srmklive/laravel-paypal#257]
I have data such:

```php
array:7 [▼
  0 => array:3 [▼
    "price" => 370500
    "qty" => "1"
    "name" => "style three"
  ]
  1 => array:3 [▼
    "price" => 3564000
    "qty" => "1"
    "name" => "test 2020"
  ]
  "invoice_id" => "5c6f8be9e9b2b"
  "invoice_description" => "Order #5c6f8be9e9b2b Invoice"
  "return_url" => "http://shopping.dev.com"
  "cancel_url" => "http://shopping.dev.com/my-orders"
  "total" => 3934500
]
```

# Issue

Based on this part of my function I should be able to return in PayPal website, instead I always get redirect back `catch part`

```php
try {
            $response = $provider->addOptions($options)->setExpressCheckout($data);
            return redirect($response['paypal_link']);
} catch (\Exception $e) {
            Session::flash('danger', 'something went wrong with PayPal.');
            return redirect()->back();
}
```

Here is my full function

```php
public function paypalexpressCheckout(Request $request){
        $provider = new ExpressCheckout;
        $inputids = $request->input('ids');
        $ids = explode(',',$inputids);
        $orders = Order::whereIn('ordernu', $ids)->get();
        $data = [];
        foreach($orders as $item){
          foreach($item->product_data as $itemm)
          {
            //calculate items price
            $tax = $item->tax;
            $pp = $itemm['price'];
            $pp1 = $item->shipment_price;;
            $pp2 = $pp + $pp1;
            //end calculation
            $itemdata = array(
                'price'     => (int)$pp2 * $tax / 100 + (int)$pp2,
                'qty'  => $itemm['quantity'],
                'name'      => $itemm['name'],
            );
            array_push($data, $itemdata);
          }
        }
        
        $data['invoice_id'] = uniqid();
        $data['invoice_description'] = "Order #{$data['invoice_id']} Invoice";
        $data['return_url'] = url('/');
        $data['cancel_url'] = url('/my-orders');
        $data['total'] = $orders->sum('totalprice');

        $info = Setting::all();
        foreach($info as $inf){
            $siteEmail = $inf->email;
        }
        $info2 = Design::all();
        foreach($info2 as $inf2){
            $siteLogo = $inf2->logo;
        }
        
        $options = [
            'BRANDNAME' => config('app.name'),
            'LOGOIMG' => url('images/').'/'.$siteLogo,
            'EMAIL' => $siteEmail,
        ];
        // dd($data);

        try {
            $response = $provider->addOptions($options)->setExpressCheckout($data);
            return redirect($response['paypal_link']);
        } catch (\Exception $e) {
            Session::flash('danger', 'something went wrong with PayPal.');
            return redirect()->back();
        }
    }
```

## Update

I tried to get exception error and see why is that? and I got `Undefined index: items`

Something in this file perhaps: `vendor\srmklive\paypal\src\Services\ExpressCheckout.php(164)`

here is full error:

```html
 ErrorException: Undefined index: items in C:\laragon\www\shopping\vendor\srmklive\paypal\src\Services\ExpressCheckout.php:164 Stack trace: #0 C:\laragon\www\shopping\vendor\srmklive\paypal\src\Services\ExpressCheckout.php(164): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', 'C:\\laragon\\www\\...', 164, Array) #1 C:\laragon\www\shopping\app\Http\Controllers\Front\OrderController.php(320): Srmklive\PayPal\Services\ExpressCheckout->setExpressCheckout(Array) #2 [internal function]: App\Http\Controllers\Front\OrderController->paypalexpressCheckout(Object(Illuminate\Http\Request)) #3 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): call_user_func_array(Array, Array) #4 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('paypalexpressCh...', Array) #5 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Front\OrderController), 'paypalexpressCh...') #6 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Route.php(176): Illuminate\Routing\Route->runController() #7 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Router.php(682): Illuminate\Routing\Route->run() #8 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #9 C:\laragon\www\shopping\app\Http\Middleware\NotBlocked.php(38): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #10 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): App\Http\Middleware\NotBlocked->handle(Object(Illuminate\Http\Request), Object(Closure)) #11 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #12 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Auth\Middleware\EnsureEmailIsVerified.php(28): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #13 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Auth\Middleware\EnsureEmailIsVerified->handle(Object(Illuminate\Http\Request), Object(Closure)) #14 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #15 C:\laragon\www\shopping\app\Http\Middleware\PreviewModeMiddleware.php(19): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #16 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): App\Http\Middleware\PreviewModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure)) #17 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #18 C:\laragon\www\shopping\vendor\misterphilip\maintenance-mode\src\MisterPhilip\MaintenanceMode\Http\Middleware\CheckForMaintenanceMode.php(113): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #19 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): MisterPhilip\MaintenanceMode\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure)) #20 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #21 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #22 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure)) #23 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #24 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #25 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure)) #26 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #27 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(75): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #28 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure)) #29 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #30 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #31 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #32 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #33 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #34 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #35 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #36 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #37 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure)) #38 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #39 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(66): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #40 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure)) #41 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #42 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #43 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Router.php(684): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #44 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Router.php(659): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request)) #45 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Router.php(625): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route)) #46 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Router.php(614): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request)) #47 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #48 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request)) #49 C:\laragon\www\shopping\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #50 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure)) #51 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #52 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #53 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure)) #54 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #55 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #56 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure)) #57 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #58 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #59 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure)) #60 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #61 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #62 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #63 C:\laragon\www\shopping\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request)) #64 C:\laragon\www\shopping\public\index.php(60): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request)) #65 {main} 
```

**Any idea?**

**Comment by robertnicjoo** [comment]
# Solved

I changed item parts of my function like:


```php
$data = [];
        foreach($orders as $item){
          foreach($item->product_data as $itemm)
          {
            //calculate items price
            $tax = $item->tax;
            $pp = $itemm['price'];
            $pp1 = $item->shipment_price;;
            $pp2 = $pp + $pp1;
            //end calculation
            $data['items'][] = array(
                'price'     => (int)$pp2 * $tax / 100 + (int)$pp2,
                'qty'  => $itemm['quantity'],
                'name'      => $itemm['name'],
            );
          }
        }
```

and also removed `array_push($data, $itemdata);` as long as I'm using `$data['items'][]` now it was unnecessary.


Hope it help others.
